---

- name: Install python-pycurl
  yum: name=python-pycurl state=installed

- name: Import jenkins key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    state: present
    validate_certs: no

- name: Get jenkins repo for ansible
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
